### ISSUE TITLE
ValueError: Found array with 0 sample(s) (shape=(0,)) while a minimum of 1 is required.

### ISSUE THREAD

**Issue by gitv806** [scitime/scitime#59]
**Describe the bug**
On running the sample code in the README for running _model.py, if I pass in save_model as True in the model_fit() call, I get the following error:

> 
> Traceback (most recent call last):
>   File "//main.py", line 8, in <module>
>     meta_algo = trainer.model_fit(generate_data=False, inputs=inputs, outputs=outputs, save_model=True)
>   File "\\path_to_project\venv\lib\site-packages\scitime\_log.py", line 25, in timed
>     result = method(*args, **kw)
>   File "\\path_to_project\venv\lib\site-packages\scitime\_model.py", line 524, in model_fit
>     mse_tests = [mean_squared_error(y_test[bin], y_pred_test[bin])
>   File "\\path_to_project\venv\lib\site-packages\scitime\_model.py", line 524, in <listcomp>
>     mse_tests = [mean_squared_error(y_test[bin], y_pred_test[bin])
>   File "\\path_to_project\venv\lib\site-packages\sklearn\utils\validation.py", line 63, in inner_f
>     return f(*args, **kwargs)
>   File "\\path_to_project\venv\lib\site-packages\sklearn\metrics\_regression.py", line 335, in mean_squared_error
>     y_type, y_true, y_pred, multioutput = _check_reg_targets(
>   File "\\path_to_project\venv\lib\site-packages\sklearn\metrics\_regression.py", line 89, in _check_reg_targets
>     y_true = check_array(y_true, ensure_2d=False, dtype=dtype)
>   File "\\path_to_project\venv\lib\site-packages\sklearn\utils\validation.py", line 63, in inner_f
>     return f(*args, **kwargs)
>   File "\\path_to_project\venv\lib\site-packages\sklearn\utils\validation.py", line 669, in check_array
>     raise ValueError("Found array with %d sample(s) (shape=%s) while a"
> ValueError: Found array with 0 sample(s) (shape=(0,)) while a minimum of 1 is required.
> 
> Process finished with exit code 1

**To Reproduce**

```
from scitime._model import Model

# example of data generation for rf regressor
trainer = Model(drop_rate=0.99999, verbose=3, algo='RandomForestRegressor')
inputs, outputs, _ = trainer._generate_data()

# then fitting the meta model
meta_algo = trainer.model_fit(generate_data=False, inputs=inputs, outputs=outputs, save_model=True)
```

**Expected behavior**
No ValueError to be thrown

**Suggestion**

I suspect, in the following code on line 518 of _model.py, 

```
    mse_tests = [mean_squared_error(y_test[bin], y_pred_test[bin])
                 for bin in bins_values]
```

that when bin is False and y_test is empty, sklearn/validate.py throws the error.

Was the intention to do something like this:

```
    mse_tests=[]
    for bin in bins_values:
        if (y_test[bin].size>0):
            mse_tests.append(mean_squared_error(y_test[bin], y_pred_test[bin]))
```

**Comment by nathan-toubiana** [comment]
hi @gitv806 , thanks for posting! yes indeed this happens when some buckets are empty. we ll work on fix asap.
